spring:
  application:
    name: myriadapi
  servlet:
    multipart: #file upload settings - change to new name space spring.http.multipart.
      file-size-threshold: 1MB
      max-file-size: 1MB
      max-request-size: 10MB
  datasource: # DATASOURCE
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.104.225.39/gift_dev?serverTimezone=GMT%2B8&useServerPrepStmts=true
    username: root
    password: ydZuAqfy$**133
    hikari:
      auto-commit: true
      connection-test-query: SELECT 1
      connection-timeout: 30000
      idle-timeout: 30000
      max-lifetime: 540000
      maximum-pool-size: 5
      pool-name: DatebookHikariCP    
      
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        format_sql: true
        use_sql_comments: true
        globally_quoted_identifiers: true
        generate_statistics: true
        order_inserts: true
        order_updates: true
        jdbc:
          batch_size: 25
          batch_versioned_data: true
  messages:
      basename: i18n/messages
      fallback-to-system-locale: true
  output.ansi.enabled: ALWAYS

# cache server
  cache:
    type: redis
    redis:
      time-to-live: 1800000
      cache-null-value: false
  redis:
    host: localhost
    port: 6379
    password:
    database: 0

myriad:
  http:
    auth-token-header-name: x-app-id
  oidc:
    token-url: https://keycloak-test.xinongtech.com/auth/realms/myriad/protocol/openid-connect/token
    client-id: myriadapi-server
    client-secret: d7d73922-1943-4f29-b97f-0287a7b7fa4c
  ribbon:
    listOfServers: https://myriad-test.xinongtech.com/api/v1/    

feign:
  client:
    config:
      myriad:
        read-timeout: 5000
        request-interceptors:
          - feign.RequestInterceptor
        logger-level: full
logging:
  level:
    org.springframework: INFO
    io.chainmind: INFO

server:
  port: 8181
  session-timeout: 30000
  tomcat:
    max-threads: 1000
    uri-encoding: UTF-8
  http2:
    enabled: true
  compression:
    enabled: true
    
  