spring:  
  cloud:
    consul:
      host: 127.0.0.1
      port: 8500  
    stream:
      kafka:
        binder:
          brokers: host:9092
          autoCreateTopics: false
          headerMapperBeanName: customHeaderMapper
      bindings:
        input:
          binder: kafka
          destination: myriad.event.Organization  
          group: myriad-organization    
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: https://[host]/auth/realms/myriad/protocol/openid-connect/certs
          user-name-attribute: preferred_username
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://[host]/myriad?serverTimezone=GMT%2B8
    username: root
    password: [changeme]
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        globally_quoted_identifiers: true

logging:
  level:
    org.springframework: INFO
    io.chainmind: DEBUG

