spring:
  profiles:
    active: dev
  application:
    name: myriadapi
  servlet:
    multipart: #file upload settings - change to new name space spring.http.multipart.
      file-size-threshold: 1MB
      max-file-size: 1MB
      max-request-size: 10MB
  datasource: # DATASOURCE
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://[host]/gift_dev?serverTimezone=GMT%2B8&useServerPrepStmts=true
    username: root
    password: [changeme]
    hikari:
      auto-commit: true
      connection-test-query: SELECT 1
      connection-timeout: 30000
      idle-timeout: 30000
      max-lifetime: 540000
      maximum-pool-size: 5
      pool-name: DatebookHikariCP    
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        globally_quoted_identifiers: true
        generate_statistics: true
        order_inserts: true
        order_updates: true
        jdbc:
          batch_size: 25
          batch_versioned_data: true
  messages:
      basename: i18n/messages
      fallback-to-system-locale: true
  output.ansi.enabled: ALWAYS

myriad:
  oidc:
    token-url: https://[host]/auth/realms/myriad/protocol/openid-connect/token
    client-id: myriadapi-server
    client-secret: [changeme]
  ribbon:
    listOfServers: https://[host]/api/v1/    
feign:
  client:
    config:
      myriad:
        read-timeout: 5000
        request-interceptors:
          - feign.RequestInterceptor
        error-decoder: io.chainmind.gift.client.MyriadClientErrorDecoder
        logger-level: full
logging:
  level:
    org.springframework: INFO
    io.chainmind: INFO

